http:
 #region routers 
  routers:
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.local.alexgrieco.io`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: proxmox
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.local.alexgrieco.io`)"
      middlewares:
        - default-headers
        - pihole-redirect
      tls: {}
      service: pihole 
#endregion
#region services
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://10.13.13.2:8006"
        passHostHeader: true
    pihole:
      loadBalancer:
        servers:
          - url: "http://10.2.0.7:8001"
        passHostHeader: true
#endregion
  middlewares:
    pihole-redirect:
      redirectRegex:
        regex: "^https?://pihole.local.alexgrieco.io/$"
        replacement: "https://pihole.local.alexgrieco.io/admin/"
    https-redirect:
      redirectScheme:
        scheme: https
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
